name = "TCCFunctions"
uuid = "3ff2cf41-83c0-4ad8-89c5-b261aa1afc74"
authors = ["renilsonlisboa <renilsonlisboajunior@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GenieFramework = "a59fdf5c-6bf0-4f5d-949c-a137c9e2f353"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
CSV = "0.10.15"
DataFrames = "1.7.0"
GenieFramework = "2.4.0"
XLSX = "0.10.4"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
